In [1]:
# To make sure the created documents are at hte project root level
import os
os.chdir(os.path.dirname(os.path.dirname(os.path.abspath("__file__"))))
print(os.getcwd())

C:\Users\israe\Documentos\Quant Reseach Ecosystem\quant-data-engine

In [2]:
# Make sure any update to imported module reloads automatically
%load_ext autoreload
%autoreload 2

In [3]:
# Fetch and store data
from qde.storage import save_ohlcv
save_ohlcv("BTCUSDT", source="binance", start="2015-01-01")
save_ohlcv("SPY", source="yfinance", start="2015-01-01")

[*********************100%***********************]  1 of 1 completed

'data\\ohlcv\\SPY_yfinance_1d.parquet'

In [4]:
# Load stored data (no API call, instant)
from qde.storage import load_ohlcv_local

print("about to load")
df = load_ohlcv_local("BTCUSDT", source="binance")
print(f"loaded: {len(df)} rows")
print(df.head())

about to load
loaded: 3230 rows
                              open     high      low    close       volume
date
2017-08-17 00:00:00+00:00  4261.48  4485.39  4200.74  4285.08   795.150377
2017-08-18 00:00:00+00:00  4285.08  4371.52  3938.77  4108.37  1199.888264
2017-08-19 00:00:00+00:00  4108.37  4184.69  3850.00  4139.98   381.309763
2017-08-20 00:00:00+00:00  4120.98  4211.08  4032.62  4086.29   467.083022
2017-08-21 00:00:00+00:00  4069.13  4119.62  3911.79  4016.00   691.743060

In [5]:
# Query with SQL via DuckDB
from qde.storage import query

df = query("SELECT date, close FROM BTCUSDT_binance_1d WHERE close > 60000")
print(df.head())

                       date     close
0 2021-03-13 00:00:00+00:00  61188.39
1 2021-04-11 01:00:00+01:00  60002.43
2 2021-04-13 01:00:00+01:00  63575.00
3 2021-04-14 01:00:00+01:00  62959.53
4 2021-04-15 01:00:00+01:00  63159.98

In [6]:
# Update with only new data
from qde.storage import update_ohlcv

update_ohlcv("BTCUSDT", source="binance")

BTCUSDT already up to date through 2026-06-20

In [7]:
from qde.storage import query
print(query("SELECT count(*) as rows FROM BTCUSDT_binance_1d"))
print(query("SELECT count(*) as rows FROM SPY_yfinance_1d"))

   rows
0  3230
   rows
0  2882

In [8]:
# Check the state of the btc data in storage
from qde.storage import load_ohlcv_local

df = load_ohlcv_local('BTCUSDT', source='binance')
print(f'Rows: {len(df)}')
print(f'Date range: {df.index.min()} to {df.index.max()}')
print(df.head(10))
print(df.tail(10))
print(df.dtypes)
print(df.isnull().sum())

Rows: 3230
Date range: 2017-08-17 00:00:00+00:00 to 2026-06-20 00:00:00+00:00
                              open     high      low    close       volume
date
2017-08-17 00:00:00+00:00  4261.48  4485.39  4200.74  4285.08   795.150377
2017-08-18 00:00:00+00:00  4285.08  4371.52  3938.77  4108.37  1199.888264
2017-08-19 00:00:00+00:00  4108.37  4184.69  3850.00  4139.98   381.309763
2017-08-20 00:00:00+00:00  4120.98  4211.08  4032.62  4086.29   467.083022
2017-08-21 00:00:00+00:00  4069.13  4119.62  3911.79  4016.00   691.743060
2017-08-22 00:00:00+00:00  4016.00  4104.82  3400.00  4040.00   966.684858
2017-08-23 00:00:00+00:00  4040.00  4265.80  4013.89  4114.01  1001.136565
2017-08-24 00:00:00+00:00  4147.00  4371.68  4085.01  4316.01   787.418753
2017-08-25 00:00:00+00:00  4316.01  4453.91  4247.48  4280.68   573.612740
2017-08-26 00:00:00+00:00  4280.71  4367.00  4212.41  4337.44   228.108068
                               open      high       low     close       volume
date
2026-06-11 00:00:00+00:00  61510.99  63933.02  61510.99  63625.99  17380.94642
2026-06-12 00:00:00+00:00  63626.00  64394.44  62829.81  63580.01  16397.05240
2026-06-13 00:00:00+00:00  63580.00  64762.77  63418.66  64458.01   9960.74163
2026-06-14 00:00:00+00:00  64458.01  65800.00  63678.83  65746.45  13203.03375
2026-06-15 00:00:00+00:00  65746.45  67292.15  65354.00  66328.74  18559.80102
2026-06-16 00:00:00+00:00  66328.74  66992.00  65360.92  65675.01  14302.05801
2026-06-17 00:00:00+00:00  65675.02  66445.93  63915.77  64509.40  19048.65409
2026-06-18 00:00:00+00:00  64509.40  64806.00  62272.07  62958.01  16935.59661
2026-06-19 00:00:00+00:00  62958.01  63666.00  62316.44  63543.91  14247.42400
2026-06-20 00:00:00+00:00  63543.90  64388.00  63184.21  63902.26   8309.01292
open      float64
high      float64
low       float64
close     float64
volume    float64
dtype: object
open      0
high      0
low       0
close     0
volume    0
dtype: int64

In [9]:
# Check the state of the spy data in storage
from qde.storage import load_ohlcv_local

df = load_ohlcv_local('SPY', source='yfinance')
print(f'Rows: {len(df)}')
print(f'Date range: {df.index.min()} to {df.index.max()}')
print(df.head(10))
print(df.tail(10))
print(df.dtypes)
print(df.isnull().sum())

Rows: 2882
Date range: 2015-01-02 00:00:00+00:00 to 2026-06-18 00:00:00+00:00
                                 open        high         low       close  \
date
2015-01-02 00:00:00+00:00  170.472589  170.885595  168.655350  169.687866
2015-01-05 00:00:00+00:00  168.647066  168.812266  166.317716  166.623337
2015-01-06 00:00:00+00:00  166.928919  167.449311  164.260901  165.053879
2015-01-07 00:00:00+00:00  166.375506  167.449325  165.929464  167.110657
2015-01-08 00:00:00+00:00  168.514916  170.290852  168.498405  170.076080
2015-01-09 00:00:00+00:00  170.489104  170.505628  168.101926  168.713181
2015-01-12 00:00:00+00:00  168.845332  169.002276  166.788555  167.391541
2015-01-13 00:00:00+00:00  168.605807  169.729186  165.623899  166.920746
2015-01-14 00:00:00+00:00  164.913498  166.111227  164.021415  165.912979
2015-01-15 00:00:00+00:00  166.548976  166.862852  164.277440  164.393082

                              volume
date
2015-01-02 00:00:00+00:00  121465900
2015-01-05 00:00:00+00:00  169632600
2015-01-06 00:00:00+00:00  209151400
2015-01-07 00:00:00+00:00  125346700
2015-01-08 00:00:00+00:00  147217800
2015-01-09 00:00:00+00:00  158567300
2015-01-12 00:00:00+00:00  144396100
2015-01-13 00:00:00+00:00  214553300
2015-01-14 00:00:00+00:00  192991100
2015-01-15 00:00:00+00:00  176613900
                                 open        high         low       close  \
date
2026-06-05 00:00:00+00:00  750.376868  750.885567  733.640017  735.654785
2026-06-08 00:00:00+00:00  741.449811  743.424764  736.293113  737.320435
2026-06-09 00:00:00+00:00  741.719176  744.980793  720.733262  735.156067
2026-06-10 00:00:00+00:00  731.505486  736.482654  723.466199  723.565918
2026-06-11 00:00:00+00:00  726.887384  738.098492  722.548526  735.864258
2026-06-12 00:00:00+00:00  738.806688  742.527084  733.141291  739.843994
2026-06-15 00:00:00+00:00  749.917997  754.735603  749.828262  752.890381
2026-06-16 00:00:00+00:00  752.611105  753.498832  747.953122  748.401978
2026-06-17 00:00:00+00:00  749.359442  750.217279  737.320450  739.056030
2026-06-18 00:00:00+00:00  747.760010  748.229980  743.859985  746.739990

                             volume
date
2026-06-05 00:00:00+00:00  93989400
2026-06-08 00:00:00+00:00  49319100
2026-06-09 00:00:00+00:00  87683500
2026-06-10 00:00:00+00:00  60341300
2026-06-11 00:00:00+00:00  86330500
2026-06-12 00:00:00+00:00  57079500
2026-06-15 00:00:00+00:00  60176400
2026-06-16 00:00:00+00:00  67093100
2026-06-17 00:00:00+00:00  85945200
2026-06-18 00:00:00+00:00  80875700
open      float64
high      float64
low       float64
close     float64
volume      int64
dtype: object
open      0
high      0
low       0
close     0
volume    0
dtype: int64

In [10]:
import pandas as pd
from qde.storage import load_ohlcv_local

df = load_ohlcv_local('BTCUSDT', source='binance')

full_range = pd.date_range(df.index.min(), df.index.max(), freq='D', tz='UTC')
missing = full_range.difference(df.index)
print(missing[:10])

DatetimeIndex([], dtype='datetime64[ms, UTC]', freq='D')

In [11]:
import pandas as pd
from qde.storage import load_ohlcv_local

df = load_ohlcv_local('SPY', source='yfinance')

full_range = pd.date_range(df.index.min(), df.index.max(), freq='D', tz='UTC')
missing = full_range.difference(df.index)
print(missing[:10].dayofweek)

Index([5, 6, 5, 6, 5, 6, 0, 5, 6, 5], dtype='int32')

In [12]:
from qde.quality import check_gaps

btc = load_ohlcv_local("BTCUSDT", source="binance")
spy = load_ohlcv_local("SPY", source="yfinance")

print(f"BTC gaps: {len(check_gaps(btc, calendar='crypto'))}")
print(f"SPY gaps: {len(check_gaps(spy, calendar='equity'))}")

BTC gaps: 0
SPY gaps: 0

In [13]:
df = load_ohlcv_local("BTCUSDT", source="binance")
print(df.index.duplicated().sum())
print(df[df.index.duplicated(keep=False)])

0
Empty DataFrame
Columns: [open, high, low, close, volume]
Index: []

In [14]:
df = load_ohlcv_local("SPY", source="yfinance")
print(df.index.duplicated().sum())
print(df[df.index.duplicated(keep=False)])

0
Empty DataFrame
Columns: [open, high, low, close, volume]
Index: []

In [15]:
from qde.quality import check_duplicates
spy = load_ohlcv_local("SPY", source="yfinance")
btc = load_ohlcv_local("BTCUSDT", source="binance")

btc_dupli = check_duplicates(btc)
spy_dupli = check_duplicates(spy)

print(btc_dupli)
print(spy_dupli)

Empty DataFrame
Columns: [open, high, low, close, volume]
Index: []
Empty DataFrame
Columns: [open, high, low, close, volume]
Index: []

In [16]:
# Find null rows
df = load_ohlcv_local("BTCUSDT", source="binance")
print(df.isnull().sum())

open      0
high      0
low       0
close     0
volume    0
dtype: int64

In [17]:

# Find null rows
df = load_ohlcv_local("SPY", source="yfinance")
print(df.isnull().sum())

open      0
high      0
low       0
close     0
volume    0
dtype: int64

In [18]:
# Check for nulls
from qde.quality import check_nulls
spy = load_ohlcv_local("SPY", source="yfinance")
spy_null = check_nulls(spy)
print(spy_null)

open      0
high      0
low       0
close     0
volume    0
dtype: int64

In [19]:
# Check for nulls
from qde.quality import check_nulls
btc = load_ohlcv_local("BTCUSDT", source="binance")
btc_null = check_nulls(btc)
print(btc_null)

open      0
high      0
low       0
close     0
volume    0
dtype: int64

In [20]:
# Price sanity
from qde.storage import load_ohlcv_local
from qde.quality import check_price_sanity

from qde.quality import check_nulls
btc = load_ohlcv_local("BTCUSDT", source="binance")
spy = load_ohlcv_local("SPY", source="yfinance")

btc_sanity = check_price_sanity(btc)
spy_sanity = check_price_sanity(spy)

print(btc_sanity)
print(spy_sanity)

Empty DataFrame
Columns: [open, high, low, close, volume]
Index: []
Empty DataFrame
Columns: [open, high, low, close, volume]
Index: []

In [21]:
# Status check

from qde.quality import run_quality_report
from qde.storage import load_ohlcv_local

btc = load_ohlcv_local("BTCUSDT", source="binance")
spy = load_ohlcv_local("SPY", source="yfinance")

run_quality_report(btc, name="BTCUSDT_binance_1d", calendar="crypto")
print()
run_quality_report(spy, name="SPY_yfinance_1d", calendar="equity")

====== Quality Report: BTCUSDT_binance_1d ======

Gaps:             0
Duplicates:       0
Nulls:            0
Price issues:     0
Status:           CLEAN

====== Quality Report: SPY_yfinance_1d ======

Gaps:             0
Duplicates:       0
Nulls:            0
Price issues:     0
Status:           CLEAN

True

In [22]:
# Check nyse calendar for number if trading days
import pandas_market_calendars as mcal

nyse = mcal.get_calendar("NYSE")
schedule = nyse.schedule(start_date="2015-01-01", end_date="2026-06-18")
print(f'Trading days: {len(schedule)}')
print(schedule.head())

Trading days: 2882
                         market_open              market_close
2015-01-02 2015-01-02 14:30:00+00:00 2015-01-02 21:00:00+00:00
2015-01-05 2015-01-05 14:30:00+00:00 2015-01-05 21:00:00+00:00
2015-01-06 2015-01-06 14:30:00+00:00 2015-01-06 21:00:00+00:00
2015-01-07 2015-01-07 14:30:00+00:00 2015-01-07 21:00:00+00:00
2015-01-08 2015-01-08 14:30:00+00:00 2015-01-08 21:00:00+00:00

In [23]:
# Check current data to compare the number of trading days

from qde.storage import load_ohlcv_local

spy = load_ohlcv_local("SPY", source="yfinance")
print(f'SPY rows: {len(spy)}')
print(f'NYSE trading days in range: {len(schedule)}')

SPY rows: 2882
NYSE trading days in range: 2882

In [24]:
import pandas_market_calendars as mcal

nyse = mcal.get_calendar("NYSE")
schedule = nyse.schedule(start_date="2024-01-01", end_date="2024-02-01")
print(schedule.index.tz)

None

In [25]:
from pathlib import Path

files =  list((Path("data") / "ohlcv").glob("*.parquet"))
for file in files:
    print(file.stem)

BTCUSDT_binance_1d
SPY_yfinance_1d

In [26]:
# Split file name

name = "BTCUSDT_binance_1d"
parts = name.split("_")
print(parts)

['BTCUSDT', 'binance', '1d']

In [27]:
# Grab each part

symbol = parts[0]
source = parts[1]
interval = parts[2]

print(symbol, source, interval)

BTCUSDT binance 1d

In [28]:
# Load file and compute the stats
import pandas as pd

df = pd.read_parquet(files[0])
print(f"Rows: {len(df)}")
print(f"First: {df.index.min()}")
print(f"Last: {df.index.max()}")
print(f"Days stale: {(pd.Timestamp.now(tz='UTC') - df.index.max()).days}")

Rows: 3230
First: 2017-08-17 00:00:00+00:00
Last: 2026-06-20 00:00:00+00:00
Days stale: 0

In [29]:
# Run the quality checks and build one row

from qde.quality import check_gaps, check_nulls, check_duplicates, check_price_sanity

gaps = check_gaps(df, calendar="crypto")
duplicates = check_duplicates(df)
nulls = check_nulls(df)
price_issues = check_price_sanity(df)

row = {
    "symbol": symbol,
    "source": source,
    "interval": interval,
    "total_rows": len(df),
    "first_date": df.index.min(),
    "last_date": df.index.max(),
    "days_stale": (pd.Timestamp.now(tz="UTC") - df.index.max()).days,
    "gaps": len(gaps),
    "duplicates": len(duplicates),
    "nulls": nulls.sum(),
    "price_issues": len(price_issues),
}

row["status"] = "CLEAN" if (row["gaps"] == 0 and row["duplicates"] == 0 and row["nulls"] == 0 and row["price_issues"] == 0) else "ISSUES FOUND"

print(row)

{'symbol': 'BTCUSDT', 'source': 'binance', 'interval': '1d', 'total_rows': 3230, 'first_date': Timestamp('2017-08-17 00:00:00+0000', tz='UTC'), 'last_date': Timestamp('2026-06-20 00:00:00+0000', tz='UTC'), 'days_stale': 0, 'gaps': 0, 'duplicates': 0, 'nulls': np.int64(0), 'price_issues': 0, 'status': 'CLEAN'}

In [33]:
# Loop through all files and and collect a row for each

all_rows = []

for file in files:
    parts = file.stem.split("_")
    symbol = parts[0]
    source = parts[1]
    interval = parts[2]

    df = pd.read_parquet(file)

    # Determine calendar type
    calendar = "equity" if source == "yfinance" else "crypto"

    gaps = check_gaps(df, calendar=calendar)
    duplicates = check_duplicates(df)
    nulls = check_nulls(df)
    price_issues = check_price_sanity(df)

    row = {
        "symbol": symbol,
        "source": source,
        "interval": interval,
        "total_rows": len(df),
        "first_date": df.index.min(),
        "last_date": df.index.max(),
        "days_stale": (pd.Timestamp.now(tz="UTC") - df.index.max()).days,
        "gaps": len(gaps),
        "duplicates": len(duplicates),
        "nulls": nulls.sum(),
        "price_issues": len(price_issues),
    }
    row["status"] = "CLEAN" if (row["gaps"] == 0 and row["duplicates"] == 0 and row["nulls"] == 0 and row["price_issues"] == 0) else "ISSUES FOUND"

    all_rows.append(row)

summary = pd.DataFrame(all_rows)

summary.to_csv("data/quality_summary.csv", index=False)
summary

,symbol,source,interval,total_rows,first_date,last_date,days_stale,gaps,duplicates,nulls,price_issues,status
0,BTCUSDT,binance,1d,3230,2017-08-17 00:00:00+00:00,2026-06-20 00:00:00+00:00,0,0,0,0,0,CLEAN
1,SPY,yfinance,1d,2882,2015-01-02 00:00:00+00:00,2026-06-18 00:00:00+00:00,2,0,0,0,0,CLEAN

In [37]:
from qde.quality import build_quality_summary

summary = build_quality_summary()
summary

,symbol,source,interval,total_rows,first_date,last_date,days_stale,gaps,duplicates,nulls,price_issues,status
0,BTCUSDT,binance,1d,3230,2017-08-17 00:00:00+00:00,2026-06-20 00:00:00+00:00,0,0,0,0,0,CLEAN
1,SPY,yfinance,1d,2882,2015-01-02 00:00:00+00:00,2026-06-18 00:00:00+00:00,2,0,0,0,0,CLEAN